#!/usr/bin/env python3
"""Generate the per-version Gradle modules from gradle/versions.gradle.

The version matrix is the single source of truth. Each target needs only two
generated files:

    versions/<mc>/build.gradle                  which Loom plugin, then apply the shared script
    versions/<mc>/src/main/resources/fabric.mod.json   with the version's own dependency bounds

...plus a project entry in settings.gradle. Generating them keeps the 16 targets
from drifting apart, and makes adding a version a one-line change.

Usage:
    python tools/generate_modules.py
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MATRIX = os.path.join(ROOT, "gradle", "versions.gradle")

# 'v1_21_1'  : [mc: '1.21.1',  era: '1.21',   java: 21, api: '0.116.17+1.21.1',  loader: '0.19.5', remap: true],
ENTRY = re.compile(
    r"'(?P<name>v[\w]+)'\s*:\s*\[\s*"
    r"mc:\s*'(?P<mc>[^']+)'\s*,\s*"
    r"era:\s*'(?P<era>[^']+)'\s*,\s*"
    r"java:\s*(?P<java>\d+)\s*,\s*"
    r"api:\s*'(?P<api>[^']+)'\s*,\s*"
    r"loader:\s*'(?P<loader>[^']+)'\s*,\s*"
    r"remap:\s*(?P<remap>true|false)\s*\]"
)


def read_matrix():
    with open(MATRIX, encoding="utf-8") as handle:
        text = handle.read()
    targets = []
    for match in ENTRY.finditer(text):
        targets.append(match.groupdict())
    if not targets:
        sys.exit("No targets parsed from gradle/versions.gradle — check the format.")
    return targets


BUILD_GRADLE = """plugins {{
	// {comment}
	id '{plugin}' version "${{loom_version}}"
}}

apply from: rootProject.file('gradle/target-module.gradle')
"""

# The manifest every module gets. Note "environment": "*" rather than "server":
# Fabric does not load a "server" mod on a physical client at all
# (ModEnvironment.SERVER.matches(CLIENT) is false), which silently excludes
# single-player — where the integrated server is the only place the trade logic
# could run, and where a player testing the mod will actually be. There is no
# client-side code in this project, so loading on a client means only that the
# server-side callbacks have nothing to do; vanilla-client compatibility does not
# depend on it, since the other players' clients never load anything of ours.
FABRIC_MOD = """{{
	"schemaVersion": 1,
	"id": "tradewindow",
	"version": "${{version}}",
	"name": "Trade Window",
	"description": "Secure, server-authoritative player-to-player trading. Two players open a shared window, both lock their side, and the items swap atomically — no scamming, no dropped items, no desync. Vanilla clients only: the mod adds no items, blocks, entities or packets.",
	"authors": [
		"Trade Window contributors"
	],
	"contact": {{
		"sources": "https://github.com/tradewindow/tradewindow"
	}},
	"license": "MIT",
	"icon": "assets/tradewindow/icon.png",
	"environment": "*",
	"entrypoints": {{
		"main": [
			"com.tradewindow.TradeWindow"
		]
	}},
	"depends": {{
		"fabricloader": ">={loader}",
		"fabric-api": "*",
		"minecraft": "${{minecraft_version}}",
		"java": ">={java}"
	}}
}}
"""

SETTINGS_HEAD = """pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'tradewindow'

// ---------------------------------------------------------------------------
// One module per Minecraft version, generated by tools/generate_modules.py from
// the matrix in gradle/versions.gradle. Do not hand-edit the includes below.
//
// Targets sharing an `era` also share one source tree under eras/, so the code
// that moves items is written once per API surface rather than once per version.
//
//   ./gradlew buildAll        build every target
//   ./gradlew :v1_21_1:build  build one target
// ---------------------------------------------------------------------------

include 'shared'
"""


def main():
    targets = read_matrix()

    lines = [SETTINGS_HEAD]
    for target in targets:
        name, mc = target["name"], target["mc"]
        module_dir = os.path.join(ROOT, "versions", mc)
        os.makedirs(os.path.join(module_dir, "src", "main", "resources"), exist_ok=True)

        if target["remap"] == "true":
            plugin = "net.fabricmc.fabric-loom-remap"
            comment = ("Minecraft {} is obfuscated: remapping Loom plugin, official Mojang "
                       "mappings, modImplementation.").format(mc)
        else:
            plugin = "net.fabricmc.fabric-loom"
            comment = ("Minecraft {} is unobfuscated: plain Loom plugin, NO mappings line, "
                       "implementation.").format(mc)

        with open(os.path.join(module_dir, "build.gradle"), "w", encoding="utf-8") as handle:
            handle.write(BUILD_GRADLE.format(comment=comment, plugin=plugin))

        with open(os.path.join(module_dir, "src", "main", "resources", "fabric.mod.json"),
                  "w", encoding="utf-8") as handle:
            handle.write(FABRIC_MOD.format(loader=target["loader"], java=target["java"]))

        lines.append(f"include '{name}'")
        lines.append(f"project(':{name}').projectDir = file('versions/{mc}')")
        lines.append("")

    with open(os.path.join(ROOT, "settings.gradle"), "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))

    print(f"Generated {len(targets)} version modules:")
    for target in targets:
        kind = "obfuscated" if target["remap"] == "true" else "unobfuscated"
        print(f"  {target['name']:10} mc={target['mc']:8} era={target['era']:7} "
              f"java={target['java']:3} {kind:13} api={target['api']}")


if __name__ == "__main__":
    main()
